pipeline 
{
    agent any

    stages 
    {
        stage('Compile Stage') 
        {
            steps 
            {
               withMaven(maven : 'MAVEN_HOME'){
               bat 'mvn clean compile' 
            }
        }
     }

        stage('Test') 
        {
            steps 
            {
               withMaven(maven : 'MAVEN_HOME'){
               bat 'mvn test'
            }
        }
      }

        stage('Email Notification') 
        {
            steps 
            {
               mail bcc: '', body: '''Hii,
               Please find the result''', cc: '', from: '', replyTo: '', subject: 'Report from Jenkins', to: 'josejibin173@gmail.com'
            }
        }
    }

    
   
   } 
    
}
