pipeline 
{
    agent any

    stages 
    {
        stage('Compile Stage') 
        {
            steps 
            {
               withMaven(maven : 'MAVEN_HOME'){
               sh 'mvn clean compile' 
            }
        }

        stage('Test') 
        {
            steps 
            {
               withMaven(maven : 'MAVEN_HOME')
               sh 'mvn test'
            }
        }

        stage('Deploy') 
        {
            steps 
            {
               withMaven(maven : 'MAVEN_HOME'){
               sh 'mvn deploy'
            }
        }
    }

    post
    {

    	always
    	{
    		emailext body: 'Summary', subject: 'Pipeline Status', to: 'selenium3bymukesh@gmail.com'
    	}

    }
}
